import urllib.request
import json
import sys

if len(sys.argv) < 2:
    print("Usage: python verify_sms.py <code_number>")
    sys.exit(1)

code = sys.argv[1]

# Load previous response data (generated by request_sms.py, so it's clean JSON)
try:
    with urllib.request.urlopen("http://127.0.0.1:5000/api/sms-login/verify-code") as _:
        pass # just checking connectivity
except:
    pass

with open('response.json', 'r') as f:
    prev_data = json.load(f)

url = "http://127.0.0.1:5000/api/sms-login/verify-code"
data = {
    "phoneNumber": "+17143329798",
    "code": code,
    "phoneHash": prev_data['phoneHash'],
    "sessionString": prev_data['sessionString']
}
headers = {"Content-Type": "application/json"}

req = urllib.request.Request(url, data=json.dumps(data).encode('utf-8'), headers=headers)

try:
    with urllib.request.urlopen(req) as response:
        print(response.read().decode('utf-8'))
except urllib.error.HTTPError as e:
    print(f"Error: {e.read().decode('utf-8')}")
except Exception as e:
    print(f"Error: {str(e)}")
